// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 AbuKaram01

//! Strategy 2: compress non-image content streams that have no filter
//! applied at all.
//!
//! Content streams (page-drawing instructions: text positioning, paths,
//! colors) are frequently written uncompressed by PDF generators.
//! Wrapping them in plain Deflate is a quick, lossless win.

use flate2::{write::ZlibEncoder, Compression};
use lopdf::{Object, Stream};
use std::io::Write;

/// Returns `true` if `stream` has no `Filter` entry, is not an image
/// (images are handled separately by `images.rs`), and isn't a
/// PDF-internal structural stream (the cross-reference stream or a
/// compressed-object container) — those get wholesale regenerated by
/// the writer on every save, so touching them here would be pointless
/// at best and could conflict with that regeneration at worst.
pub fn is_uncompressed(stream: &Stream) -> bool {
    let is_image = stream
        .dict
        .get(b"Subtype")
        .map(|o| matches!(o, Object::Name(n) if n.as_slice() == b"Image"))
        .unwrap_or(false);

    if is_image {
        return false;
    }

    let is_internal_structure = matches!(
        stream.dict.get(b"Type"),
        Ok(Object::Name(n)) if n.as_slice() == b"XRef" || n.as_slice() == b"ObjStm"
    );
    if is_internal_structure {
        return false;
    }

    stream.dict.get(b"Filter").is_err()
}

/// Compresses a filter-less stream with Deflate (`FlateDecode`).
///
/// Returns `None` if compression doesn't actually shrink the stream
/// (can happen with very small streams, where the zlib header/footer
/// overhead outweighs the savings).
pub fn compress_stream(stream: &Stream) -> Option<(Stream, i64)> {
    if stream.content.is_empty() {
        return None;
    }

    let original_len = stream.content.len();

    let mut encoder = ZlibEncoder::new(Vec::new(), Compression::best());
    encoder.write_all(&stream.content).ok()?;
    let compressed = encoder.finish().ok()?;

    let saved = original_len as i64 - compressed.len() as i64;
    if saved <= 0 {
        return None;
    }

    let new_len = compressed.len() as i64;
    let mut new_stream = stream.clone();
    new_stream.content = compressed;
    new_stream
        .dict
        .set("Filter", Object::Name(b"FlateDecode".to_vec()));
    new_stream.dict.set("Length", Object::Integer(new_len));

    Some((new_stream, saved))
}

#[cfg(test)]
mod tests {
    use super::*;
    use lopdf::Dictionary;

    /// Builds a minimal stream with an optional `/Type` and `/Filter`,
    /// for exercising [`is_uncompressed`]'s exclusion rules.
    fn stream_with(type_name: Option<&[u8]>, filter: Option<&[u8]>) -> Stream {
        let mut dict = Dictionary::new();
        if let Some(t) = type_name {
            dict.set("Type", Object::Name(t.to_vec()));
        }
        if let Some(f) = filter {
            dict.set("Filter", Object::Name(f.to_vec()));
        }
        Stream::new(dict, b"some bytes".to_vec())
    }

    #[test]
    fn xref_stream_is_never_treated_as_compressible_content() {
        let s = stream_with(Some(b"XRef"), None);
        assert!(
            !is_uncompressed(&s),
            "an XRef stream must be excluded regardless of its Filter"
        );
    }

    #[test]
    fn objstm_stream_is_never_treated_as_compressible_content() {
        let s = stream_with(Some(b"ObjStm"), None);
        assert!(!is_uncompressed(&s));
    }

    #[test]
    fn a_genuine_unfiltered_content_stream_is_still_flagged() {
        let s = stream_with(None, None);
        assert!(
            is_uncompressed(&s),
            "a real content stream with no Type/Filter must still be flagged"
        );
    }

    #[test]
    fn a_filtered_content_stream_is_not_flagged() {
        let s = stream_with(None, Some(b"FlateDecode"));
        assert!(!is_uncompressed(&s));
    }
}
